name: Publish DBUtils on PyPI

on:
  push:
    tags:
      - 'Release-*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build tool
      run: python -m pip install build --user

    - name: Build source tarball and wheel
      run: python -m build

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
